name: ToDoApiBuildAndDeploy
variables:
  acrConnection: 'AcrConnection'
  k8Connection: 'K8Connection'
  imageRepository: 'todoapi'
  dockerFilePath: '$(Build.SourcesDirectory)/TodoApi/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'secret'

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - TodoApi/*

stages:
- stage: Build
  displayName: Build and push to ACR
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerFilePath)
        containerRegistry: $(acrConnection)
        tags: |
          $(tag)
    - publish: '$(Build.SourcesDirectory)/Manifests'
      displayName: Publish Kubernetes Manifest Files
      artifact: manifests

- stage: Deploy
  displayName: Deploy the container
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'windows-latest'
    environment: 'spike.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: manifests
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(acrConnection)
              kubernetesServiceConnection: $(k8Connection)
              namespace: 'default'
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: $(k8Connection)
              namespace: 'default'
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                acrpoc4543423.azurecr.io/todoapi:$(tag)