apiVersion : apps/v1
kind: Deployment
metadata:
  name: todoapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapi
  template:
    metadata:
      labels:
        app: todoapi
    spec:
      containers:
        - name: todoapi
          image: acrpoc4543423.azurecr.io/todoapi:latest
          ports:
          - containerPort: 5001